### ISSUE TITLE
Does this display the NFT I own on OpenSea?

### ISSUE THREAD

**Issue by uditswaroopa** [AudiusProject/fetch-nft#14]
Hey Devs
Hope you all are doing great, I see in this project you have OpenSea assets API to get all the NFT's a user owns from wallet address. The question is **does this API displays NFT's minted and then owned from other platforms** like super rare, looks rare, etc. Basically OpenSea competitors? 
Looking forward to hearing back from you thank you! 

Best Regards
Udit

**Comment by raymondjacobson** [comment]
Yes it does! Let us know if there are specific NFTs you have a hard time connecting.
